### ISSUE TITLE
Проблемы со ссылками

### ISSUE THREAD

**Issue by aliona5252** [Flibustiers/flibustiers.github.io#1]
На главной странице не работают ссылки на социалку, нет паблика в телеге, или вы собрались людей в наш чат присоединять, я не поняла? Кнопка скачать не работает

**Comment by DanilTech** [comment]
Есть
![image](https://user-images.githubusercontent.com/67013355/227751916-d0ac1369-d12d-47f2-a0d4-71e1b94eb64c.png)
